routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Profile\AvatarController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TicketRepliesController;
use Laravel\Socialite\Facades\Socialite;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Models\Ticket;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    // $user = DB::statement("select * from users");
    // $user = DB::select("select * from users");
    // $user = DB::select("select * from users where id=1");
    // $user = DB::select("select * from users where email=?",['ambalavanan@essopl.in']);
    // $user = DB::insert("insert into users (name, email, password) values (?,?,?)" ,['moorthi','ambalavanantesting@essopl.in','testing']);
    // $user = DB::insert("update users set email='ambalavanantest@essopl.in' where id=3");
    // $user = DB::insert("delete from users where id=3");
    // $user = DB::table('users')->get();
    // $user = DB::table('users')->first();
    // $user = DB::table('users')->where('id',3)->first();
    // $user = DB::table('users')->insert([
    //     'name' => 'testuser',
    //     'email' => 'testuser@test.com',
    //     'password' => 'testing'
    // ]);
    // $user = DB::table('users')->where('id',3)->update([
    //     'name' => 'testuser1',
    //     'email' => 'testuser1@test.com',
    // ]);
    // $user = DB::table('users')->where('id',3)->delete();
    // $user = User::get();
    // $user = User::create([
    //         'name' => 'testuser2',
    //         'email' => 'testuser2@test.com',
    //         'password' => 'testing'
    // ]);
    // $user = User::where('id',2)->update([
    //     'name' => 'testuser3',
    //     'email' => 'testuser3@test.com',
    // ]);
    // $user = User::find(3);
    // $user->update([
    //     'email' => 'testuser4@test.com',
    // ]);
    // $user = User::all();

    // $user = User::create([
    //             'name' => 'testuser5',
    //             'email' => 'testuse5@test.com',
    //             'password' => bcrypt('testing')
    //     ]);

    // $user = User::find(3);
    //     // dd($user);
    // dd($user->name);

    return view('welcome');
});

Route::get('/dashboard', function () {
    $user    = auth()->user();
    $open = $user->isAdmin ? Ticket::where('status','open')->count() : $user->tickets->where('status','open')->count();
    $resolved = $user->isAdmin ? Ticket::where('status','resolved')->count() : $user->tickets->where('status','resolved')->count();
    $approved = $user->isAdmin ? Ticket::where('status','approved')->count() : $user->tickets->where('status','approved')->count();
    $rejected = $user->isAdmin ? Ticket::where('status','rejected')->count() : $user->tickets->where('status','rejected')->count();
    $data = [
        'open'     => $open,
        'resolved' => $resolved,
        'approved' => $approved,
        'rejected' => $rejected,
    ];
    return view('dashboard',compact('data'));
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::patch('/profile/avatar', [AvatarController::class, 'update'])->name('avatar.profile.update');
    Route::post('/profile/openai', [AvatarController::class, 'generate'])->name('avatar.profile.generate');
    
});

Route::post('/auth/redirect', function () {
    return Socialite::driver('github')->redirect();
})->name('login.github');
 
Route::get('/auth/callback', function () {
    $user = Socialite::driver('github')->stateless()->user();
    //dd($user);
    $user = User::updateOrCreate(['email' => $user->email], [
        'name' => isset($user->name)?$user->name:$user->nickname,
        'password' => '12345678'
    ]);
    //dd($user);
    Auth::login($user);
    return redirect('/dashboard');
});

Route::middleware('auth')->group(function () {
    Route::resource('/ticket',TicketController::class);
});

Route::middleware('auth')->group(function () {
    Route::resource('/ticket_replay',TicketRepliesController::class);
});



require __DIR__.'/auth.php';

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'status',
        'attachment',
        'user_id',
        'status_changed_by_id'		

    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ticket;
use App\Models\TicketReplies;
use App\Http\Requests\StoreTicketRequest;
use App\Http\Requests\UpdateTicketRequest;
use Illuminate\Support\str;
use Illuminate\Support\Facades\Storage;
use App\Notifications\TicketUpdatedNotification;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user    = auth()->user();
        $tickets = $user->isAdmin ? Ticket::latest()->get() : $user->tickets;
        return view('ticket.index', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('Ticket.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreTicketRequest $request)
    {
        $ticket = Ticket::create([
            'title'       => $request->title,
            'description' => $request->description,
            'user_id'     => auth()->id(),
        ]);

        if ($request->file('attachment')) {
            $this->storeAttachment($request, $ticket);
        }

        return redirect(route('ticket.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Ticket $ticket)
    {
        //dd( $ticket->id);
        $ticket_replay = TicketReplies::with('user')->where('ticket_id',$ticket->id)->get();
        //dd($ticket_replay);
        return view('ticket.show', compact('ticket','ticket_replay'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Ticket $ticket)
    {
        return view('ticket.edit', compact('ticket'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateTicketRequest $request, Ticket $ticket)
    {
       // dd("Test");
        $ticket->update($request->except('attachment'));
        if ($request->has('status')) {
            // $user = User::find($ticket->user_id);
            $ticket->user->notify(new TicketUpdatedNotification($ticket));
        }
        if ($request->file('attachment')) {
            Storage::disk('public')->delete($ticket->attachment);
            $this->storeAttachment($request, $ticket);
        }
        return redirect(route('ticket.index'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Ticket $ticket)
    {
        $ticket->delete();
        return redirect(route('ticket.index'));
    }

    protected function storeAttachment($request, $ticket)
    {
        $ext      = $request->file('attachment')->extension();
        $contents = file_get_contents($request->file('attachment'));
        $filename = Str::random(25);
        $path     = "attachments/$filename.$ext";
        Storage::disk('public')->put($path, $contents);
        $ticket->update(['attachment' => $path]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/Ticket/create.blade.php
<x-app-layout>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
        <h1 class="text-white text-lg font-bold">Create new support ticket</h1>
        <div class="w-full sm:max-w-xl mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg">
            <form method="POST" action="{{ route('ticket.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="mt-4">
                    <x-input-label for="title" :value="__('Title')" />
                    <x-text-input id="title" class="block mt-1 w-full" type="text" name="title" autofocus />
                    <x-input-error :messages="$errors->get('title')" class="mt-2" />
                </div>

                <div class="mt-4">
                    <x-input-label for="description" :value="__('Description')" />
                    <x-textarea placeholder="Add description" name="description" id="description" value="" />
                    <x-input-error :messages="$errors->get('description')" class="mt-2" />
                </div>

                <div class="mt-4">
                    <x-input-label for="attachment" :value="__('Attachment')" />
                    <x-file-input name="attachment" id="attachment" />
                    <x-input-error :messages="$errors->get('attachment')" class="mt-2" />
                </div>

                <div class="flex items-center justify-end mt-4">
                    <x-primary-button class="ml-3">
                        Create
                    </x-primary-button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/Ticket/edit.blade.php
<x-app-layout>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
        <h1 class="text-white text-lg font-bold">Update support ticket</h1>
        <div class="w-full sm:max-w-xl mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg">
            <form method="POST" action="{{ route('ticket.update', $ticket->id) }}" enctype="multipart/form-data">
                @csrf
                @method('patch')
                <!-- Email Address -->
                <div class="mt-4">
                    <x-input-label for="title" :value="__('Title')" />
                    <x-text-input id="title" class="block mt-1 w-full" type="text" name="title" autofocus
                        value="{{ $ticket->title }}" />
                    <x-input-error :messages="$errors->get('title')" class="mt-2" />
                </div>

                <div class="mt-4">
                    <x-input-label for="description" :value="__('Description')" />
                    <x-textarea placeholder="Add description" name="description" id="description"
                        value="{{ $ticket->description }}" />
                    <x-input-error :messages="$errors->get('description')" class="mt-2" />
                </div>

                <div class="mt-4">
                    @if ($ticket->attachment)
                        <a href="{{ '/storage/' . $ticket->attachment }}" style="color:blue" target="_blank">See
                            Attachment</a>
                    @endif
                    <x-input-label for="attachment" :value="__('Attachment (if any)')" />
                    <x-file-input name="attachment" id="attachment" />
                    <x-input-error :messages="$errors->get('attachment')" class="mt-2" />
                </div>

                <div class="flex items-center justify-end mt-4">
                    <x-primary-button class="ml-3">
                        Update
                    </x-primary-button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/Ticket/index.blade.php
<x-app-layout>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
        <div class="flex justify-between w-full sm:max-w-xl">
            <h1 class=" text-lg font-bold" style="color:white;">Support Tickets</h1>
            <div>
                <a href="{{ route('ticket.create') }}" class="bg-white rounded-lg p-2">Create New</a>
            </div>
        </div>
        <div class="w-full sm:max-w-xl mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg">
            @forelse ($tickets as $ticket)
                <div class=" flex justify-between py-4">
                    <a href="{{ route('ticket.show', $ticket->id) }}">{{ $ticket->title }}</a>
                    <p>{{ $ticket->created_at->diffForHumans() }}</p>
                </div>
            @empty
                <p class="">You don't have any support ticket yet.</p>
            @endforelse
        </div>
    </div>
</x-app-layout>

resources/views/Ticket/show.blade.php
<x-app-layout>
<div class="row">
<div class="col-md-6 col-xl-6">
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
        <h1 class="text-white text-lg font-bold">{{ $ticket->title }}</h1>
        <div class="w-full sm:max-w-xl mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg">
            <div class=" flex justify-between py-4">
                <p>{{ $ticket->description }}</p>
                <p>{{ $ticket->created_at->diffForHumans() }}</p>
                @if ($ticket->attachment)
                    <a href="{{ '/storage/' . $ticket->attachment }}" target="_blank">Attachment</a>
                @endif
            </div>

            <div class="flex justify-between">
                <div class="flex">
                    <a href="{{ route('ticket.edit', $ticket->id) }}">
                        <x-primary-button>Edit</x-primary-button>
                    </a>

                    <form class="ml-2" action="{{ route('ticket.destroy', $ticket->id) }}" method="post">
                        @method('delete')
                        @csrf
                        <x-primary-button>Delete</x-primary-button>
                    </form>
                </div>
                @if (auth()->user()->isAdmin)
                    <div class="flex">
                        <form action="{{ route('ticket.update', $ticket->id) }}" method="post">
                            @csrf
                            @method('patch')
                            <input type="hidden" name="status" value="approved" />
                            <x-primary-button>Approve</x-primary-button>
                        </form>
                        <form action="{{ route('ticket.update', $ticket->id) }}" method="post">
                            @csrf
                            @method('patch')
                            <input type="hidden" name="status" value="resolved" />
                            <x-primary-button>Resolved</x-primary-button>
                        </form>
                        <form action="{{ route('ticket.update', $ticket->id) }}" method="post">
                            @csrf
                            @method('patch')
                            <input type="hidden" name="status" value="rejected" />
                            <x-primary-button class="ml-2">Reject</x-primary-button>
                        </form>
                    </div>
                @else
                    <p class="">Status: {{ $ticket->status }} </p>
                @endif
            </div>
        </div>
    </div>
    </div>
    <div class="col-md-6 col-xl-6">

<!------ Include the above in your HEAD tag ---------->
					<div class="card" style="height:650px;">
						<div class="card-header msg_head">
							<div class="d-flex bd-highlight">
								<div class="user_info">
									<span>Comments</span>
									<p>{{count($ticket_replay)}} Messages</p>
								</div>
							</div>
						</div>
						<div class="card-body msg_card_body">
                        @if(count($ticket_replay) == 0)
                        <p class="text-center">No message here</p>
                        @else
                        @foreach($ticket_replay as $data)

                        @if($data->user_id == auth()->id())
                            <div class="d-flex justify-content-end mb-4">
							<div class="msg_cotainer_send">
                            <p class="text-decoration-underline action_menu_btn" style="font-size:12px;cursor:pointer;">{{$data->user->name}}</p>
                            {{$data->description}}
							<span class="msg_time">{{ $data->created_at->diffForHumans() }}</span>
							</div>
                            </div>

                            <!-- <div class="action_menu">
								<ul>
									
                                    <form class="ml-2" action="{{ route('ticket_replay.destroy', $data->id) }}" method="post">
                                        @method('delete')
                                        @csrf
									<li><i class="fas fa-ban"></i><button>Delete</button></li>
                                    </form>
								</ul>
							</div> -->


                        @else
                            <div class="d-flex justify-content-start mb-4">
							<div class="msg_cotainer">
                            <p class="text-decoration-underline action_menu_btn" style="font-size:12px;">{{$data->user->name}}</p>
                            {{$data->description}}
							<span class="msg_time">{{ $data->created_at->diffForHumans() }}</span>
							</div>
							</div>

                        @endif	
                            @endforeach
						</div>
                        @endif
						<div class="card-footer">
                        <form method="POST" action="{{ route('ticket_replay.store') }}" enctype="multipart/form-data">
                        @csrf
							<div class="input-group">
                                <input type="hidden" name="ticket_id" value="{{$ticket->id}}">
                                <input type="hidden" name="edit_flag" value="0">
								<textarea name="description" class="form-control" placeholder="Type your message..." required></textarea>
								<div class="input-group-append">
									<span class="input-group-text send_btn"><button>Reply</button></span>
								</div>
							</div>
                            </form>
						</div>
					</div>
				
	
    </div>
    </div>
</x-app-layout>
<script>

$(document).ready(function(){
$('.action_menu_btn').click(function(){
	$('.action_menu').toggle();
});

$(".editBtn").click(function(){
  console.log(this);
});

	});


</script>